### ISSUE TITLE
Problem with updating fields in `Piccolo User` via admin panel

### ISSUE THREAD

**Issue by jrycw** [sinisaos/headless-forum-fastapi#4] opened 2024-03-15 07:32 UTC
Firstly, thank you for providing this helpful template for us to follow along.

However, I've encountered a couple of issues during this process:

It appears that we're unable to update certain fields in `Piccolo User` using the admin panel. For example, when attempting to update the `email` field, the screen shows that the update is successful, but the field does not actually update.

Additionally, it seems that performing a bulk update in `Piccolo User`, such as updating the `first name` field, is not functioning correctly. The screen displays "Invalid column name or value", and the traceback indicates:
```python
".../piccolo_api/crud/endpoints.py", line 1162, in patch_single
    if values["password"]:
       ~~~~~~^^^^^^^^^^^^
KeyError: 'password'
```

I'm curious whether the issue originates from `piccolo_api` or from the example itself. Any insights you could provide would be greatly appreciated.

**Comment by sinisaos** [comment] 2024-03-15 09:45
@jrycw Thank you for your kind words.The problem is not with this repo, but with the Piccolo API. As far as I can see, the problem is in [this code](https://github.com/piccolo-orm/piccolo_api/blob/09e9f958ff87d7dbdd015227129102cf03f90f8a/piccolo_api/crud/endpoints.py#L1157-L1169). That code works fine when the admin user wants to change the password, but it doesn't work when the Piccolo BaseUser is updated and bulk updated.
That code should be changed to something like this `piccolo_api/crud/endpoints.py` and you can patch a local Piccolo API installation and see if it works. In my case everything works fine.
```python
@apply_validators
@db_exception_handler
async def patch_single(
    self, request: Request, row_id: PK_TYPES, data: t.Dict[str, t.Any]
) -> Response:
    """
    Patch a single row.
    """
    cleaned_data = self._clean_data(data)

    try:
        model = self.pydantic_model_optional(**cleaned_data)
    except pydantic.ValidationError as exception:
        return Response(str(exception), status_code=400)

    cls = self.table

    try:
        values = {
            getattr(cls, key): getattr(model, key)
            for key in data.keys()
        }
    except AttributeError:
        unrecognised_keys = set(data.keys()) - set(
            model.model_dump().keys()
        )
        return Response(
            f"Unrecognised keys - {unrecognised_keys}.",
            status_code=400,
        )

    if self._hook_map:
        values = await execute_patch_hooks(
            hooks=self._hook_map,
            hook_type=HookType.pre_patch,
            row_id=row_id,
            values=values,
            request=request,
        )

    try:
        if issubclass(cls, BaseUser):
            # if password is changed
            if values["password"]:
                cls._validate_password(values["password"])
                values["password"] = cls.hash_password(values["password"])
            else:
                # use previous password
                values.pop("password")
        await cls.update(values).where(
            cls._meta.primary_key == row_id
        ).run()
        new_row = (
            await cls.select(exclude_secrets=self.exclude_secrets)
            .where(cls._meta.primary_key == row_id)
            .first()
            .run()
        )
        assert new_row
        return CustomJSONResponse(
            self.pydantic_model(**new_row).model_dump_json()
        )
    except ValueError:
        return Response(
            "Unable to save the resource.", status_code=500
        )
```
Hope that helps.

**Comment by jrycw** [comment] 2024-03-15 12:52
@sinisaos Thank you for your prompt response.

I've conducted tests using the provided code, and it seems to have resolved the first issue. However, we're still encountering a `KeyError` when attempting to bulk update fields other than the `password`. Additionally, the `test_patch_user_fails` case is failing.

Upon inspection, it appears that the issue stems from the line `values["password"]`. It seems that values is a dictionary with only one key-value pair during bulk updates. If we're not updating the `password` field, this line may do nothing but raise a `KeyError`.

To address this, I made a slight adjustment to the logic as follows:
```python
    try:    
        if issubclass(cls, BaseUser):
            if password:= values.pop("password", None):
                cls._validate_password(password)
                values["password"] = cls.hash_password(password)
        ...
```
From my perspective, this adjustment resolves the issue. However, the `test_patch_user_fails` case still fails.
```python
        with self.assertRaises(ValueError):
            response = client.patch(f"/{user['id']}/", json=json)
>           self.assertEqual(response.content, b"The password is too short.")
E           AssertionError: b'Unable to save the resource.' != b'The password is too short.'
tests/crud/test_crud_endpoints.py:268: AssertionError
```

**Comment by jrycw** [comment] 2024-03-15 13:11
@sinisaos I've tested a modified version of the code, and it appears to be functioning correctly. What are your thoughts on this approach?
```python
  @apply_validators
  @db_exception_handler
  async def patch_single(
      self, request: Request, row_id: PK_TYPES, data: t.Dict[str, t.Any]
  ) -> Response:
      """
      Patch a single row.
      """
      cleaned_data = self._clean_data(data)

      try:
          model = self.pydantic_model_optional(**cleaned_data)
      except pydantic.ValidationError as exception:
          return Response(str(exception), status_code=400)

      cls = self.table

      try:
          values = {getattr(cls, key): getattr(model, key) for key in data.keys()}
      except AttributeError:
          unrecognised_keys = set(data.keys()) - set(model.model_dump().keys())
          return Response(
              f"Unrecognised keys - {unrecognised_keys}.",
              status_code=400,
          )

      if self._hook_map:
          values = await execute_patch_hooks(
              hooks=self._hook_map,
              hook_type=HookType.pre_patch,
              row_id=row_id,
              values=values,
              request=request,
          )

      if issubclass(cls, BaseUser):
          if password := values.pop("password", None):
              cls._validate_password(password)
              values["password"] = cls.hash_password(password)
      try:
          await cls.update(values).where(cls._meta.primary_key == row_id).run()
          new_row = (
              await cls.select(exclude_secrets=self.exclude_secrets)
              .where(cls._meta.primary_key == row_id)
              .first()
              .run()
          )
          assert new_row
          return CustomJSONResponse(self.pydantic_model(**new_row).model_dump_json())
      except ValueError:
          return Response("Unable to save the resource.", status_code=500)
```
While the modified code appears to be functional, I can't help but feel it's a bit unconventional to bulk update fields subject to a unique constraint. The current implementation will attempt to modify the first field and subsequently fail the rest of the operation.

**Comment by sinisaos** [comment] 2024-03-15 22:21
@jrycw Sorry, I didn't run a unit test, I just tried it with the cloned repo and everythig works (but without of password validation). You are correct, password validation failed. I just removed the suggested code from the try block and all the unit tests pass because then the validation is executed. After that, the problem you mentioned, about unique columns appeared. Piccolo is correct about bulk update unique columns and I prevent error by put pass in `KeyError` exception like this (I don't know if this is the right way, but it does update, bulk update and change password work)
```python
if issubclass(cls, BaseUser):
    try:
        # if password is changed
        if values["password"]:
            cls._validate_password(values["password"])
            values["password"] = cls.hash_password(values["password"])
        else:
            # use previous password
            values.pop("password")
    except KeyError:
        pass

try:
    await cls.update(values).where(
...
```
You have to open an issue in Piccolo API and refer to this issue because the maintainer has to say what he thinks about this.

**Comment by jrycw** [comment] 2024-03-16 00:44
@sinisaos Thank you for your valuable feedback. I'll go ahead and open an issue in the Piccolo API repository to reference this problem.

**Comment by sinisaos** [comment] 2024-03-21 06:35
Closed this issue as the discussion has been moved to the Piccolo API repo.

**Closed as completed by sinisaos** 2024-03-21 06:35 UTC
